 meta_product_name: "CoRent"
 meta_title: "CoRent - Share your space, not your time"
 meta_description: "CoRent is the ultimate solution for separated parents who want to share an apartment without the stress of coordinating schedules or seeing each other. Our app allows you to co-parent efficiently and harmoniously, ensuring your child's well-being and stability while maintaining your personal space and peace of mind."
 meta_image: "cover.jpg"
